export const EXTENSION_MAP: Record<string, string> = {
    // Web languages
    javascript: 'js',
    js: 'js',
    typescript: 'ts',
    ts: 'ts',
    jsx: 'jsx',
    tsx: 'tsx',
    html: 'html',
    xhtml: 'html',
    xml: 'xml',
    css: 'css',
    scss: 'scss',
    sass: 'sass',
    less: 'less',
    json: 'json',
    yaml: 'yml',
    yml: 'yml',

    // Interpreted languages
    python: 'py',
    py: 'py',
    ruby: 'rb',
    rb: 'rb',
    perl: 'pl',
    pl: 'pl',
    php: 'php',
    bash: 'sh',
    shell: 'sh',
    sh: 'sh',
    powershell: 'ps1',
    ps1: 'ps1',
    batch: 'bat',
    bat: 'bat',
    cmd: 'bat',

    // Compiled languages
    java: 'java',
    c: 'c',
    cpp: 'cpp',
    'c++': 'cpp',
    csharp: 'cs',
    'c#': 'cs',
    cs: 'cs',
    golang: 'go',
    go: 'go',
    rust: 'rs',
    rs: 'rs',
    swift: 'swift',
    kotlin: 'kt',
    kt: 'kt',
    scala: 'scala',
    'objective-c': 'm',
    objc: 'm',
    haskell: 'hs',
    hs: 'hs',

    // Databases
    sql: 'sql',
    plsql: 'pls',
    tsql: 'sql',

    // Markdown and text
    markdown: 'md',
    md: 'md',
    tex: 'tex',
    latex: 'tex',
    asciidoc: 'adoc',
    adoc: 'adoc',

    // Configuration and utilities
    dockerfile: 'dockerfile',
    makefile: 'mk',
    toml: 'toml',
    ini: 'ini',
    graphql: 'gql',
    gql: 'gql',
    protobuf: 'proto',
    proto: 'proto',

    // Other
    actionscript: 'as',
    ada: 'ada',
    assembly: 'asm',
    asm: 'asm',
    clojure: 'clj',
    clj: 'clj',
    cobol: 'cob',
    dart: 'dart',
    elixir: 'ex',
    ex: 'ex',
    erlang: 'erl',
    erl: 'erl',
    fortran: 'f90',
    groovy: 'groovy',
    julia: 'jl',
    lisp: 'lisp',
    lua: 'lua',
    matlab: 'm',
    ocaml: 'ml',
    ml: 'ml',
    pascal: 'pas',
    pas: 'pas',
    r: 'r',
    scheme: 'scm',
    solidity: 'sol',
    sol: 'sol',
    vba: 'vba',
    vbnet: 'vb',
    vb: 'vb',
    webassembly: 'wasm',
    wasm: 'wasm'
} as const
