export { registerCourseIpcHandlers } from './course.ipc'
export { registerFolderIpcHandlers } from './folder.ipc'
export { registerLessonIpcHandlers } from './lesson.ipc'
export { registerProgressIpcHandlers } from './progress.ipc'
export { registerUserIpcHandlers } from './user.ipc'
